#!/usr/bin/env bash
# Regenerates .rfc/index.md from the header of every .rfc/<dir>/*.md file.
#
# Read from each file:
#   - title:  the first `# ` line
#   - status: `Statut : X` (RFC line `<date> · @author · Statut : X`) or `**Status:** X`
#   - date:   the date of the RFC line, otherwise the date the file was added to git
#
# Run by the pre-commit hook (.githooks/pre-commit) and by `task rfc:index`.
set -euo pipefail

root=$(git rev-parse --show-toplevel)
rfc_dir="$root/.rfc"
out="$rfc_dir/index.md"

# Escapes `|` so a value cannot break the table
cell() { sed 's/|/\\|/g' <<<"$1"; }

{
  echo "# RFC index"
  echo
  echo "<!-- Generated by scripts/rfc-index.sh, do not edit. -->"
  echo
  echo "| Dossier | Document | Statut | Date |"
  echo "|---|---|---|---|"
  for f in "$rfc_dir"/*/*.md; do
    rel=${f#"$rfc_dir"/}
    title=$(grep -m1 '^# ' "$f" | sed 's/^# //')
    status=$(grep -m1 -oP '(Statut :|\*\*Status:?\*\*:?) \K.*' "$f" || true)
    date=$(grep -m1 -oP '^[A-Z][a-z]{2} [0-9]{1,2}, [0-9]{4}(?= ·)' "$f" || true)
    if [[ -n $date ]]; then
      date=$(date -d "$date" +%F)
    else
      date=$(git -C "$root" log --diff-filter=A --format=%as -- "$f" | tail -1)
    fi
    echo "| ${rel%%/*} | [$(cell "${title:-${rel#*/}}")]($rel) | $(cell "${status:-?}") | ${date:-?} |"
  done
} >"$out"
